language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker
  
before_install:
  - curl -o 'settings.xml' 'http://nexus.wdf.sap.corp:8081/nexus/service/local/templates/settings/LeanDI/content' 

script:
  - mvn clean install -s settings.xml
